data <- read.table("household_power_consumption.txt", header=T, sep=";", na.strings=c("?"))
subdata <- subset(data,data$Date == "1/2/2007" | data$Date == "2/2/2007")
png("plot1.png")
hist(subdata$Global_active_power, col="red", xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()